// The printings dataset: one row per physical printing of a card (base art,
// alt art, per-set reprints). Generated by `scripts/fetch-printings.ts` into
// `data/printings.json` and joined against `data/cards.json` by `cardId`.
// Collection metadata lives here, never in cards.json or the engine types.

import { z } from 'zod'
import rawPrintings from '../../data/printings.json'
import { formatZodIssues } from '../collection/format'

export interface Printing {
  /** The app's stable printing id: `"<setCode>/<collectorNumber>"`, or
   *  `"<setCode>/<collectorNumber>/<finish>"` when `finish` is not null. See
   *  `printingKey`. */
  key: string
  /** FK into cards.json ids (the API slug). */
  cardId: string
  setCode: string
  setName: string
  /** Verbatim, including the β prefix on beta numbers. */
  collectorNumber: string
  /** Open string on purpose — the API's vocabulary is not under our control. */
  rarity: string
  finish: string | null
  artist: string
  /** The API's printing uuid, for provenance and re-sync. */
  sourcePrintingId: string
}

const printingSchema = z.object({
  key: z.string().min(1),
  cardId: z.string().min(1),
  setCode: z.string().min(1),
  setName: z.string().min(1),
  collectorNumber: z.string().min(1),
  rarity: z.string().min(1),
  finish: z.string().nullable(),
  artist: z.string(),
  sourcePrintingId: z.string().min(1),
})

const printingsSchema = z.array(printingSchema)

export { formatZodIssues } from '../collection/format'

/**
 * The app's stable printing id. `finish` participates only when it is
 * present, so every row in the dataset as generated today (all `finish:
 * null`) keeps its historical `setCode/collectorNumber` key byte for byte —
 * saved collections never need a migration. The moment upstream ships a
 * variant finish sharing a collector number with its normal card (spec §1.1
 * explicitly anticipates "a foil finish at retail"), the finish segment
 * keeps the two rows distinct instead of colliding into a duplicate key that
 * would block regenerating the dataset at all.
 *
 * Deliberately duplicated by hand in `scripts/fetch-printings.ts` (which must
 * not import this module — see that file's header); `tests/data/printings.test.ts`
 * is the drift-catcher.
 */
export function printingKey(
  setCode: string,
  collectorNumber: string,
  finish: string | null
): string {
  return finish === null
    ? `${setCode}/${collectorNumber}`
    : `${setCode}/${collectorNumber}/${finish}`
}

/** Validates raw JSON into `Printing[]`; throws with a readable message on
 *  malformed rows or duplicate keys. Used by both the loader (Task 3) and the
 *  fetch script's self-check. */
export function parsePrintings(raw: unknown): Printing[] {
  const result = printingsSchema.safeParse(raw)
  if (!result.success) {
    throw new Error(`printings.json is malformed:\n${formatZodIssues(result.error)}`)
  }
  const seen = new Set<string>()
  for (const printing of result.data) {
    if (seen.has(printing.key)) {
      throw new Error(`printings.json has a duplicate key: "${printing.key}".`)
    }
    seen.add(printing.key)
  }
  return result.data
}

export function printingsByCard(printings: Printing[]): Map<string, Printing[]> {
  const byCard = new Map<string, Printing[]>()
  for (const printing of printings) {
    const list = byCard.get(printing.cardId) ?? []
    list.push(printing)
    byCard.set(printing.cardId, list)
  }
  return byCard
}

export function getPrinting(printings: Printing[], key: string): Printing | undefined {
  return printings.find((printing) => printing.key === key)
}

/** Unique sets in first-appearance order (printings.json is written sorted
 *  by set, so this is also a stable display order). */
export function listSets(printings: Printing[]): { code: string; name: string }[] {
  const seen = new Set<string>()
  const sets: { code: string; name: string }[] = []
  for (const printing of printings) {
    if (seen.has(printing.setCode)) continue
    seen.add(printing.setCode)
    sets.push({ code: printing.setCode, name: printing.setName })
  }
  return sets
}

let loaded: Printing[] | undefined

/** The bundled dataset, parsed and validated once. Throws (with the
 *  parsePrintings message) if data/printings.json is malformed — its callers
 *  (`CollectionView`, `DeckBuilderView`) each catch that and degrade to an
 *  error state / an empty dataset respectively; only collection code imports
 *  this module, so the Play and Simulate views are untouched. */
export function loadPrintings(): Printing[] {
  if (loaded === undefined) loaded = parsePrintings(rawPrintings)
  return loaded
}
