import { test, expect } from '@playwright/test'

test('artwork and playset goals advance independently across printings', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Collection', exact: true }).click()
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
  await page.getByTestId('expand-industrial-assembly').click()
  const card = page.getByTestId('collection-count-industrial-assembly')
  await expect(card).toContainText('0/3 · Art 0/1')
  await page.getByTestId('printing-inc-arasakademodeck/006').click()
  await expect(card).toContainText('1/3 · Art 1/1')
  await page.getByTestId('printing-inc-welcometonightcityretail/033').click()
  await expect(card).toContainText('2/3 · Art 1/1')
  await expect(page.getByTestId('copy-playset-list')).toBeVisible()
  await expect(page.getByTestId('copy-artwork-list')).toBeVisible()
  const printing = page.getByTestId('printing-row-edgerunneropens1/004')
  await expect(printing).toContainText('Artwork 1 · owned')
  const image = printing.locator('img')
  await expect(image).toBeVisible()
  await expect.poll(() => image.evaluate((el: HTMLImageElement) => el.naturalWidth)).toBeGreaterThan(0)
})
