import { test,expect } from './fixtures'
test('recovers a draft acquisition, previews imports, and undoes collection changes',async({page})=>{
  await page.goto('/')
  await page.getByTestId('tab-collection').click()
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
  await page.getByTestId('collection-compact').click()
  await page.getByTestId('collection-search').fill('arasakademodeck/006')
  const initialCount=page.getByTestId('printing-count-arasakademodeck/006')
  await initialCount.fill('0');await initialCount.blur()
  await page.getByTestId('collection-mode-add').click()
  await page.getByTestId('session-source').fill('Launch boosters')
  await page.getByTestId('session-cost').fill('100 SEK')
  // The paste/exact-count panel is a collapsed <details>; open it before
  // touching anything inside (same pattern as the mobile filter rail).
  await page.getByText('Paste lines or set exact counts instead', { exact: true }).click()
  await page.getByTestId('session-input').fill('arasakademodeck/006,+3')
  await page.getByTestId('session-paste-add').click()
  await page.reload()
  await page.getByTestId('tab-collection').click()
  await expect(page.getByTestId('staged-pill')).toHaveClass(/staged-pill--stale/)
  await page.getByTestId('collection-mode-add').click()
  await expect(page.getByTestId('session-line-arasakademodeck/006')).toContainText('+3')
  await expect(page.getByTestId('session-source')).toHaveValue('Launch boosters')
  await expect(page.getByTestId('session-changes')).toContainText('0 → 3')
  await page.getByTestId('session-apply').click()
  await page.getByTestId('collection-mode-history').click()
  const acquisition=page.getByTestId('collection-history-entry').filter({hasText:'Acquisition'}).first()
  await acquisition.getByTestId('history-details').click()
  await expect(acquisition).toContainText('100 SEK')
  await acquisition.getByTestId('history-undo').click()
  await page.getByTestId('collection-mode-browse').click()
  // Browse is mounted lazily on first visit; it was never opened in this
  // browser session (mode after reload came back as 'add' from
  // sessionStorage), so it remounts here with its default grid view and no
  // drawer open -- neither renders a printing-count test id. Restore the
  // list view and search once; the component then stays mounted (hidden)
  // for every later switch back to Browse in this test.
  await page.getByTestId('collection-compact').click()
  await page.getByTestId('collection-search').fill('arasakademodeck/006')
  const count=page.getByTestId('printing-count-arasakademodeck/006')
  await expect(count).toHaveValue('0')
  await page.getByTestId('collection-mode-history').click()
  await acquisition.getByTestId('history-reapply').click()
  await page.getByTestId('collection-mode-browse').click()
  await expect(count).toHaveValue('3')
  await page.getByTestId('collection-mode-history').click()
  await page.getByTestId('import-input').fill(JSON.stringify({version:1,counts:{'arasakademodeck/006':1}}))
  await page.getByTestId('import-submit').click()
  await expect(count).toHaveValue('3')                               // Previewing an import does not write
  await expect(page.getByTestId('import-preview')).toContainText('3 → 1')
  await page.getByTestId('import-apply').click()
  await page.getByTestId('collection-mode-browse').click()
  await expect(count).toHaveValue('1')
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
})
