import { test,expect } from './fixtures'
test('searches exact printings, edits counts, and previews bulk changes on mobile',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByTestId('tab-collection').click()
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
  await page.getByTestId('collection-compact').click()
  await page.getByTestId('filter-rail').locator('summary').click()
  await page.getByTestId('collection-search').fill('Industrial 006')
  await page.getByTestId('set-filter-arasakademodeck').click()
  await expect(page.getByTestId('compact-printing')).toHaveCount(1)
  const input=page.getByTestId('printing-count-arasakademodeck/006')
  await input.fill('3');await input.blur()
  await expect(page.getByTestId('collection-scope')).toContainText('1 printing rows · 3 physical copies')
  const row=page.getByTestId('compact-printing')
  expect(await row.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  // Exact counts now live in the session (Add cards → "Set exact counts").
  await page.getByTestId('collection-mode-add').click()
  // The paste/exact-count panel is a collapsed <details>; open it before
  // touching anything inside (same pattern as the mobile filter rail).
  await page.getByText('Paste lines or set exact counts instead', { exact: true }).click()
  await page.getByTestId('session-mode-exact').click()
  await page.getByTestId('session-input').fill('arasakademodeck/006,5\nwelcometonightcityretail/033,2')
  await page.getByTestId('session-paste-add').click()
  await expect(page.getByTestId('session-changes')).toContainText('3 → 5')
  await expect(input).toBeHidden()                                   // Browse is hidden; the count is untouched until Apply
  await page.getByTestId('session-apply').click()
  await page.getByTestId('collection-mode-browse').click()
  await expect(page.getByTestId('printing-count-arasakademodeck/006')).toHaveValue('5')
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
  await page.reload()
  await page.getByTestId('tab-collection').click()
  await page.getByTestId('collection-compact').click()
  await page.getByTestId('filter-rail').locator('summary').click()
  await page.getByTestId('collection-search').fill('arasakademodeck/006')
  await expect(page.getByTestId('printing-count-arasakademodeck/006')).toHaveValue('5')
})
