import { test,expect } from '@playwright/test'
test('recovers a draft acquisition, previews imports, and undoes collection changes',async({page})=>{
  await page.goto('/')
  await page.getByTestId('tab-collection').click()
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
  await page.getByTestId('collection-compact').check()
  await page.getByTestId('collection-search').fill('arasakademodeck/006')
  const initialCount=page.getByTestId('printing-count-arasakademodeck/006')
  await initialCount.fill('0');await initialCount.blur()
  await page.getByTestId('collection-sessions').locator('summary').first().click()
  await page.getByTestId('session-source').fill('Launch boosters')
  await page.getByTestId('session-cost').fill('100 SEK')
  await page.getByTestId('session-input').fill('arasakademodeck/006,+3')
  await page.reload()
  await page.getByTestId('tab-collection').click()
  await page.getByTestId('collection-sessions').locator('summary').first().click()
  await expect(page.getByTestId('session-input')).toHaveValue('arasakademodeck/006,+3')
  await expect(page.getByTestId('session-source')).toHaveValue('Launch boosters')
  await page.getByTestId('session-preview').click()
  await expect(page.getByTestId('session-changes')).toContainText('0 → 3')
  await page.getByTestId('session-apply').click()
  await page.getByTestId('collection-history').locator('summary').first().click()
  const acquisition=page.getByTestId('collection-history-entry').filter({hasText:'Acquisition ·'})
  await acquisition.locator('summary').click()
  await expect(acquisition).toContainText('100 SEK')
  await acquisition.getByTestId('history-undo').click()
  await page.getByTestId('collection-compact').check()
  await page.getByTestId('collection-search').fill('arasakademodeck/006')
  const count=page.getByTestId('printing-count-arasakademodeck/006')
  await expect(count).toHaveValue('0')
  await acquisition.getByTestId('history-reapply').click()
  await expect(count).toHaveValue('3')
  await page.getByTestId('import-panel').locator('summary').first().click()
  await page.getByTestId('import-input').fill(JSON.stringify({version:1,counts:{'arasakademodeck/006':1}}))
  await page.getByTestId('import-submit').click()
  await expect(count).toHaveValue('3')
  await expect(page.getByTestId('import-preview')).toContainText('3 → 1')
  await page.getByTestId('import-apply').click()
  await expect(count).toHaveValue('1')
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
})
