import { test,expect } from '@playwright/test'
test('searches exact printings, edits counts, and previews bulk changes on mobile',async({page})=>{
  await page.setViewportSize({width:390,height:844})
  await page.goto('/')
  await page.getByTestId('tab-collection').click()
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
  await page.getByTestId('collection-compact').check()
  await page.getByTestId('collection-search').fill('Industrial 006')
  await page.getByTestId('set-filter').selectOption('arasakademodeck')
  await expect(page.getByTestId('compact-printing')).toHaveCount(1)
  const input=page.getByTestId('printing-count-arasakademodeck/006')
  await input.fill('3');await input.blur()
  await expect(page.getByTestId('collection-scope')).toContainText('1 printing rows · 3 physical copies')
  const row=page.getByTestId('compact-printing')
  expect(await row.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true)
  await page.getByText('Bulk printing counts',{exact:true}).click()
  await page.getByTestId('bulk-count-input').fill('arasakademodeck/006,5\nwelcometonightcityretail/033,2')
  await page.getByTestId('bulk-count-preview').click()
  await expect(page.getByTestId('bulk-count-changes')).toContainText('3 → 5')
  await expect(input).toHaveValue('3')
  await page.getByTestId('bulk-count-apply').click()
  await expect(input).toHaveValue('5')
  await expect(page.getByTestId('sync-status')).toContainText('Saved to disk')
  await page.reload()
  await page.getByTestId('tab-collection').click()
  await page.getByTestId('collection-compact').check()
  await page.getByTestId('collection-search').fill('arasakademodeck/006')
  await expect(page.getByTestId('printing-count-arasakademodeck/006')).toHaveValue('5')
})
