import { expect,test } from './fixtures'
test('samples opening cards and follows both manual-practice seats',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/?aiDelay=0')
  await page.getByTestId('tab-deckBuilder').click()
  await page.getByTestId('load-deck-button').click()
  await page.getByTestId('filter-legal-ram').check()
  await page.getByTestId('deck-diagnostics').locator('summary').click()
  await page.getByTestId('sample-hand').click()
  await expect(page.getByTestId('opening-hand').locator('.card-frame')).toHaveCount(6)
  await page.getByTestId('tab-play').click()
  await page.getByTestId('manual-practice').check()
  await page.getByTestId('seed-input').fill('42')
  await page.getByTestId('start-game').click()
  await expect(page.getByTestId('practice-seat')).toBeVisible()
  await page.getByTestId('choose-order-first').click()
  const first=await page.getByTestId('practice-seat').innerText()
  await page.getByTestId('keep-hand').click()
  await expect(page.getByTestId('practice-seat')).not.toHaveText(first)
  await expect(page.getByTestId('keep-hand')).toBeVisible()
  await expect(page.getByTestId('ai-thinking')).toHaveCount(0)
  await page.getByTestId('save-name').fill('manual position')
  await page.getByTestId('save-game').click()
  await page.getByTestId('keep-hand').click()
  await page.getByTestId('undo').click()
  await expect(page.getByTestId('keep-hand')).toBeVisible()
  await page.getByTestId('new-game').click()
  await page.getByTestId('resume-game').click()
  await expect(page.getByTestId('practice-seat')).toBeVisible()
  await expect(page.getByTestId('keep-hand')).toBeVisible()
  expect(errors).toEqual([])
})
