import { test,expect } from './fixtures'
const legends=['goro-takemura-hands-unclean','yorinobu-arasaka-embracing-destruction','saburo-arasaka-stubborn-patriarch']
test('builds within a sealed pool and retains match round-end progress',async({page})=>{
  await page.addInitScript(({legends})=>{
    if(!localStorage.getItem('ctcg:decks:v1'))localStorage.setItem('ctcg:decks:v1',JSON.stringify({'Sealed fixture':{name:'Sealed fixture',format:'sealed',legends,cards:{minotaur:30},sealedPool:{minotaur:30,...Object.fromEntries(legends.map(id=>[id,1]))}}}))
  },{legends})
  await page.goto('/')
  await page.getByTestId('tab-deckBuilder').click()
  await page.getByTestId('deck-select').selectOption('Sealed fixture')
  await page.getByTestId('load-deck-button').click()
  await expect(page.getByTestId('deck-format')).toHaveValue('sealed')
  await expect(page.getByTestId('deck-errors')).toHaveCount(0)
  await expect(page.getByTestId('filter-pool')).toBeChecked()
  await expect(page.getByTestId('filter-legal-ram')).toBeDisabled()
  await page.getByTestId('card-row-plus-minotaur').click()
  await expect(page.getByTestId('deck-errors')).toContainText('exceeds opened pool')
  await page.getByTestId('sealed-pool-input').fill(['minotaur,31',...legends.map(id=>id+',1')].join('\n'))
  await page.getByTestId('sealed-pool-apply').click()
  await expect(page.getByTestId('deck-errors')).toHaveCount(0)
  await page.getByTestId('play-this-deck').click()
  const tracker=page.getByTestId('match-tracker')
  await tracker.locator('summary').first().click()
  await page.getByTestId('match-deck-a').selectOption('Sealed fixture')
  await page.getByTestId('match-new').click()
  await page.getByTestId('match-game-0').click()
  await page.getByTestId('match-game-1').click()
  await page.getByTestId('match-call-time').click()
  await page.getByTestId('match-final-turns').click()
  await page.getByTestId('match-turn-done').click()
  await page.reload()
  await page.getByTestId('match-tracker').locator('summary').first().click()
  await expect(page.getByTestId('match-current')).toContainText('1/2 final turns completed')
  await page.getByTestId('match-turn-done').click()
  await page.getByTestId('match-gigs-a').fill('6')
  await page.getByTestId('match-finish-round').click()
  await expect(page.getByTestId('match-score')).toContainText('Match: draw')
  await expect(page.getByTestId('match-clock')).toHaveText('Match finished')
})
